apiVersion: v1
kind: ConfigMap
metadata:
  name: reception-service-config
data:
  DB_HOST: {{ .Values.env.dbHost | quote }}
  DB_PORT: {{ .Values.env.dbPort | quote }}
  DB_NAME: {{ .Values.env.dbName | quote }}
  RABBITMQ_HOST: {{ .Values.env.rabbitmqHost | quote }}
  RABBITMQ_PORT: {{ .Values.env.rabbitmqPort | quote }}
