apiVersion: v1
kind: Secret
metadata:
  name: reception-service-secret
type: Opaque
stringData:
  DB_USER: {{ .Values.postgres.user | quote }}
  DB_PASSWORD: {{ .Values.postgres.password | quote }}
  RABBITMQ_USERNAME: {{ .Values.rabbitmq.user | quote }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | quote }}
