apiVersion: v1
kind: ConfigMap
metadata:
  name: orders-service-config
data:
  SERVER_PORT: {{ .Values.env.serverPort | quote }}
  REDIS_ADDR: {{ .Values.env.redisAddr | quote }}
  REDIS_LIST_KEY: {{ .Values.env.redisListKey | quote }}
  RABBITMQ_QUEUE: {{ .Values.env.rabbitmqQueue | quote }}
